-- Tabela Frotas
CREATE TABLE IF NOT EXISTS public.frotas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa TEXT NOT NULL UNIQUE,
    modelo TEXT NOT NULL,
    tipo TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela Funcionarios
CREATE TABLE IF NOT EXISTS public.funcionarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    email TEXT,
    cargo TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela de Acessos
CREATE TABLE IF NOT EXISTS public.acessos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT,
    email TEXT NOT NULL UNIQUE,
    senha TEXT NOT NULL,
    nivel TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela Inspecoes
CREATE TABLE IF NOT EXISTS public.inspecoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa TEXT NOT NULL,
    responsavel TEXT NOT NULL,
    data TEXT NOT NULL,
    hora TEXT NOT NULL,
    mecanica JSONB,
    eletrica JSONB,
    externa JSONB,
    lubrificacao JSONB,
    calibragem JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela Preventivas
CREATE TABLE IF NOT EXISTS public.preventivas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    veiculo TEXT NOT NULL,
    plano TEXT NOT NULL,
    ultima TEXT,
    atual TEXT NOT NULL,
    intervalo TEXT NOT NULL,
    data TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela Ordens de Servico (OS)
DROP TABLE IF EXISTS public.ordens_servico;
CREATE TABLE IF NOT EXISTS public.ordens_servico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa TEXT NOT NULL,
    tipo_os TEXT NOT NULL DEFAULT 'Corretiva',
    status TEXT NOT NULL DEFAULT 'Aberta',
    data_abertura TEXT NOT NULL,
    hora_abertura TEXT NOT NULL,
    data_fechamento TEXT,
    hora_fechamento TEXT,
    prioridade TEXT NOT NULL DEFAULT 'Média',
    descricao TEXT NOT NULL,
    mecanico TEXT,
    observacoes TEXT,
    fotos_problema JSONB,
    fotos_resolvido JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Desabilitar RLS (Row Level Security) temporariamente para permitir inserts do front-end sem política complexa
ALTER TABLE public.frotas DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.funcionarios DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.acessos DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.inspecoes DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.preventivas DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.ordens_servico DISABLE ROW LEVEL SECURITY;
